### ISSUE TITLE
1.68 and auto updates

### ISSUE THREAD

**Issue by lnlyssg** [tailscale/golink#132] opened 2024-06-12 19:11 UTC
The [release notes for Tailscale 1.68](https://tailscale.com/changelog#2024-06-12) mention "Auto-updates are available for containers" so presumably if we can get an updated version of the golink container with 1.68 this should mean no more issues like #96 or #41 (or indeed this one)?

**Comment by bradfitz** [comment] 2024-07-18 15:51
cc @awly

**Comment by awly** [comment] 2024-07-18 19:54
Unfortunately, golink is a [tsnet](https://tailscale.com/kb/1244/tsnet) service, which is not the same thing as running `tailscaled` inside of a container. We do not have an auto-update mechanism for golink or tsnet services in general.

However, we need to be better about updating the Tailscale version for golink during our client releases. I'll nudge our client release owners to add it to the process.

**Comment by bgiovand** [comment] 2024-08-22 22:41
Any updates on this?

**Comment by awly** [comment] 2024-08-23 16:56
Updating `golink` is now a part of the release process, but looks like [1.72 got stuck](https://github.com/tailscale/golink/pull/136) due to some [some regressions we were chasing in 1.72.0](https://tailscale.com/changelog#2024-08-22).

Our client release team should generally keep golink up-to-date going forward, so I'll close this issue.

**Closed by awly** 2024-08-23 16:56 UTC

**Comment by lnlyssg** [comment] 2024-11-19 14:25
I think there are still issues as I've not seen any updates since 1.72.1....

**Comment by awly** [comment] 2024-11-22 22:09
@lnlyssg apologies for that, latest version has now been published.

**Comment by ItsJamesMurray** [comment] 2024-11-30 21:00
Perhaps I'm missing on how to update?  I am installed with Docker via Portainer.  

I am pulling `ghcr.io/tailscale/golink:main` and repulling for each update.  I have `'--sqlitedb' '/home/nonroot/golink.db' '--verbose'` as the command and have mounted `-v /persistent/data:/home/nonroot`.

It still shows `1.57.0-dev20240126` in Tailscale for this "machine".

**Comment by lnlyssg** [comment] 2024-11-30 21:11
Are you certain you are re-pulling? I'm also using Portainer but no issues here

**Comment by ItsJamesMurray** [comment] 2024-11-30 21:31
I sure hope so! Its how im updating my other containers and it seems to work fine.

video showing process and still out of date go machine: https://www.loom.com/share/83c8a12c0db645308a1346865d0589bc?sid=1a42fd13-65d2-4588-9321-ce7fccdb658b

**Comment by lnlyssg** [comment] 2024-11-30 21:58
Your image configuration doesn’t look right… you have dockerhub as the registry and the image field has docker.io pre-filled at the start. Can you check the Portainer logs? My guess it’s failing to pull a newer image so is just re-deploying the original one you used.

**Comment by ItsJamesMurray** [comment] 2024-11-30 22:59
Ahh i tried that and it still didn't work.  ended up SSH'ing in and running `docker pull ghcr.io/tailscale/golink:main` then finding the old image and removing it.  Sorry for the weekend blunder!
